### ISSUE TITLE
Call to undefined method ChatSession::startChat()

### ISSUE THREAD

**Issue by koossaayy** [google-gemini-php/laravel#1]
Hello, 
First of all, thank you for this package. 
I just installed it, the version `1.0.1` with PHP 8.3.1 & Laravel 10.10
and I got that error 
`
Call to undefined method Gemini\Resources\ChatSession::startChat()
`

And here is the code 

```php
    $chat = Gemini::chat()->startChat(history: [
        Content::parse(part: 'The stories you write about what I have to say should be one line. Is that clear?'),
        Content::parse(part: 'Yes, I understand. The stories I write about your input should be one line long.', role: Role::MODEL),
    ]);

    $response = $chat->sendMessage('Create a story set in a quiet village in 1600s France');
    return $response->text(); // Amidst rolling hills and winding cobblestone streets, the tranquil village of Beausoleil whispered tales of love, intrigue, and the magic of everyday life in 17th century France.

```
I hope I didn't do something wrong, or skipped something in the docs.

**Comment by aydinfatih** [comment]
Hello @koossaayy,

First of all, thank you for your feedback. There was something missing here and I fixed it in the PR below. 
Can you try again after `composer update`?


https://github.com/google-gemini-php/client/pull/5

**Comment by koossaayy** [comment]
Works like a charm. Thank you ♥
