### ISSUE TITLE
Class "App\Http\Controllers\User\Blob" not found Help me

### ISSUE THREAD

**Issue by madfortech** [google-gemini-php/laravel#10]
![Screenshot 05-17-2024 11 49 04](https://github.com/google-gemini-php/laravel/assets/21261716/43aef82c-6c5e-470a-9174-45e0fdfa84b8)
![Screenshot 05-17-2024 11 06 34](https://github.com/google-gemini-php/laravel/assets/21261716/54783f9c-952e-4c41-a198-ba76868ebd86)
![Screenshot 05-17-2024 11 07 35](https://github.com/google-gemini-php/laravel/assets/21261716/9cf76de3-60cb-468f-8200-0e00e1ca822d)
here code
![Screenshot 05-17-2024 11 51 12](https://github.com/google-gemini-php/laravel/assets/21261716/2841d79d-f65e-4739-b047-902297d86143)

**Comment by aydinfatih** [comment]
Hello @madfortech ,
There seems to be a problem with the import of the Blob class, can you try again by adding the following import?

use Gemini\Data\Blob;

**Comment by aydinfatih** [comment]
It looks wrong in this import. Can you update it as below and try?
`use Gemini\Enum\MimeType`

**Comment by atmacoder** [comment]
correct is
```
use Gemini\Enums\MimeType;
```
