### ISSUE TITLE
How do we manually specify the text model to be used.

### ISSUE THREAD

**Issue by richardksizemore** [google-gemini-php/laravel#11]
How do we specify which text model to specifically use in our requests. For example models/gemini-1.0-pro vs models/gemini-1.5-pro vs models/gemini-1.5-flash. I understand how to switch between geminiPro() and geminiProVision() but not between the different text model versions. Thanks

**Comment by aydinfatih** [comment]
Hello @richardksizemore 
You can use generativeModel method.You can pass string instead of enum to the model parameter.


```php
$gemini->generativeModel(model: ModelType::GEMINI_PRO);
```

**Comment by aydinfatih** [comment]
You are welcome. Yes, you can use it this way.
