### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by asivaneswaran** [google-gemini-php/laravel#13]
"cURL error 28: Operation timed out after 30002 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro:generateContent

I know the job is going to be long, in AI studio it takes over 30 seconds to do, so what can I do here?

**Comment by aydinfatih** [comment]
You can set the value below in your env file.

`GEMINI_REQUEST_TIMEOUT=`
