### ISSUE TITLE
error with Gemini::geminiProVision()

### ISSUE THREAD

**Issue by atmacoder** [google-gemini-php/laravel#17]
Gemini 1.0 Pro Vision has been deprecated on July 12, 2024. Consider switching to different model, for example gemini-1.5-flash.

**Comment by levizwannah** [comment]
After inspecting the code, you can use this method to select a specific model instead of using the others. 
```php
$model = Gemini::generativeModel('models/gemini-1.5-flash');
$response = $model->generate(...);
```

**Comment by aydinfatih** [comment]
I just released a new version.

Pro vision usage marked as deprecated. Also added `geminiFlash` method.

You can also use any model you want without depending on enums with the following method.
```
$client->generativeModel(model: 'models/gemini-1.5-flash-001')
```
