### ISSUE TITLE
SSL disabling

### ISSUE THREAD

**Issue by hellanya925** [google-gemini-php/laravel#2]
There is no clear method to disable ssl verification.

**Comment by backendrulz** [comment]
Where? do you have some example?

**Comment by hellanya925** [comment]
The point is im using a testing environment with no ssl certificate. Rhis
package is probably built on top of a curl request. When i try to use it, a
"no ssl certificate" error pops up.
While using native curl requests in php, we can disable ssl verification
(curl_set_opt...).

**Comment by aydinfatih** [comment]
Hello @hellanya925,
First of all, thank you for your feedback.

I think it would not be right to disable SSL requests on a package-specific basis. The problem may be related to your PHP configuration.

Can you try the solution on the site below?
https://wpquark.com/kb/misc/server-management/fixing-curl-ssl-connection-issue-php-ini/

**Comment by jhoanborges** [comment]
maybe related to guzzle: 

$this->client = new GuzzleClient(['defaults' => [
    'verify' => false
]]);
