### ISSUE TITLE
Undefined Finish Reason 

### ISSUE THREAD

**Issue by sobanshahid38** [google-gemini-php/laravel#23]
$stream = $gemini_client->geminiPro()->streamGenerateContent($prompt);
               

               

                foreach ($stream as $response) {
                    
                    $clean = str_replace(["\r\n", "\r", "\n"], "<br/>", $response->text());
                    $text .= $response->text();
                    echo 'data: ' . $clean . "\n\n";
                    ob_flush();
                    flush();
                    usleep(1400); // Optional: control streaming speed

                }  i am trying to this and  having error that undefined array key finish reason

**Comment by aydinfatih** [comment]
Thanks your feedback. The issue has been fixed.
https://github.com/google-gemini-php/client/pull/46

**Comment by sobanshahid38** [comment]
how i have tried this   just a minute ego same error
