### ISSUE TITLE
Undefined array key "license"

### ISSUE THREAD

**Issue by danjacobs1981** [google-gemini-php/laravel#25]
Every now and then I get this error... any ideas why? Thanks!

![image](https://github.com/user-attachments/assets/9443b47f-4af6-4e68-84a2-bb1302998090)

**Comment by aydinfatih** [comment]
https://github.com/google-gemini-php/client/pull/52

Hi @danjacobs1981,
This problem was fixed on November 1st. Can you please try again with `composer update`?
