### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by ahmad-nikoo** [google-gemini-php/laravel#9]
hi
when i use this code :
 ```
$result = Gemini::geminiPro()->generateContent("hello");
        $result->text();
```
i get this error :
`syntax error`     in line     `$result = Gemini::geminiPro()->generateContent("hello");`
anybody can help me?
thank's

**Comment by ahmad-nikoo** [comment]
![error](https://github.com/google-gemini-php/laravel/assets/134392921/f1935774-827f-47ad-83bb-2d3d3f7f0734)

**Comment by aydinfatih** [comment]
Hi @ahmad-nikoo ,
Can you expand the 3 vendor frames field and send the top record in that field?

**Comment by ahmad-nikoo** [comment]
yes,
![error](https://github.com/google-gemini-php/laravel/assets/134392921/6b52df13-006d-4e80-b9d7-1ffd25a76303)

**Comment by aydinfatih** [comment]
@ahmad-nikoo I could not reproduce this problem. Can you go into the source code and see the response returned from the server?

**Comment by edymarques** [comment]
Good afternoon, how are you?
I believe your issue is that you need to create a variable to receive the text.
`$result = Gemini::geminiPro()->generateContent('Hello');

$result = $result->text();
dd($result);` 
And that: or execute it directly on dd
`dd($result->text());`
And this: try this!

**Comment by aydinfatih** [comment]
When I try this, I can get a response successfully. Here the gemini api returns in a format other than json format. Therefore I need what is returned from the gemini api.

**Comment by RaminBgrn** [comment]
same issue any solution

**Comment by agunghrynt** [comment]
> same issue any solution

Add variable for '$result->text()'

Like $res = $result->text()
